services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      # BE serve anh local qua /static/images de Frontend hien thi duoc.
      - ./backend/static/images:/app/static/images
    env_file:
      - ./backend/.env
    environment:
      - AI_SERVICE_URL=http://ai_service:8001 # BÃ¡o cho BE biáº¿t chá»— gá»i AI
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
      ai_service:
        condition: service_started
    restart: unless-stopped

  ai_service:
    build:
      context: ./AI
    ports:
      - "8001:8001"
    volumes:
      - ./AI:/app
      - ./backend/static/images:/app/static/images
    environment:
      - POSTGRES_HOST=postgres
      - QDRANT_URL=http://qdrant:6333
    command: uvicorn ai_service:app --host 0.0.0.0 --port 8001
    restart: unless-stopped

  frontend:
    build:
      context: ./visual-search-fe
    ports:
      - "5173:5173"
    volumes:
      - ./visual-search-fe:/app
      - frontend_node_modules:/app/node_modules
    environment:
      VITE_API_BASE_URL: http://localhost:8000/api/v1
      VITE_ENABLE_MOCK: "false"
    depends_on:
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: visual_search
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  frontend_node_modules:
  postgres_data:
  qdrant_data:


